/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'triggerReason' : [] | [TriggerReason],
  'priceAtTrigger' : number,
  'crypto' : string,
  'timestamp' : bigint,
  'confidence' : bigint,
  'signalType' : SignalType,
}
export type Direction = { 'long' : null } |
  { 'short' : null };
export interface Position { 'quantity' : number, 'symbol' : string }
export interface Preferences { 'theme' : string, 'notifications' : boolean }
export type SignalType = { 'buy' : null } |
  { 'hold' : null } |
  { 'sell' : null };
export interface Trade {
  'id' : bigint,
  'direction' : Direction,
  'date' : string,
  'crypto' : string,
  'notes' : string,
  'rationale' : string,
  'quantity' : number,
  'entryPrice' : number,
  'exitPrice' : [] | [number],
  'outcome' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type TriggerReason = { 'trendFollowing' : boolean } |
  { 'priceBreak' : string } |
  { 'takeProfit' : [] | [number] } |
  { 'rsiBelow30' : string } |
  { 'riskReward' : [] | [number] } |
  { 'stopLoss' : [] | [number] } |
  { 'macdCrossover' : string } |
  { 'rsiAbove70' : string };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addPosition' : ActorMethod<[string, number], undefined>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'addTrade' : ActorMethod<[Trade], undefined>,
  'clearAlerts' : ActorMethod<[], undefined>,
  'fetchTopCryptoNews' : ActorMethod<[], string>,
  'fetchTopCryptos' : ActorMethod<[], string>,
  'getAlertHistory' : ActorMethod<
    [[] | [string], [] | [SignalType]],
    Array<Alert>
  >,
  'getAlertStats' : ActorMethod<[], [bigint, bigint, bigint]>,
  'getAlertsLast24Hours' : ActorMethod<[], Array<Alert>>,
  'getCryptoAlertHistory' : ActorMethod<[string], Array<Alert>>,
  'getJournal' : ActorMethod<[], Array<Trade>>,
  'getPortfolio' : ActorMethod<[], Array<Position>>,
  'getTheme' : ActorMethod<[], string>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'initializeUser' : ActorMethod<[Preferences], undefined>,
  'purgeOldAlerts' : ActorMethod<[], undefined>,
  'removeFromJournal' : ActorMethod<[bigint], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'removePosition' : ActorMethod<[string], undefined>,
  'saveAlert' : ActorMethod<
    [string, SignalType, [] | [TriggerReason], bigint, number],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTheme' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];