/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SignalType = IDL.Variant({
  'buy' : IDL.Null,
  'hold' : IDL.Null,
  'sell' : IDL.Null,
});
export const TriggerReason = IDL.Variant({
  'trendFollowing' : IDL.Bool,
  'priceBreak' : IDL.Text,
  'takeProfit' : IDL.Opt(IDL.Float64),
  'rsiBelow30' : IDL.Text,
  'riskReward' : IDL.Opt(IDL.Float64),
  'stopLoss' : IDL.Opt(IDL.Float64),
  'macdCrossover' : IDL.Text,
  'rsiAbove70' : IDL.Text,
});
export const Alert = IDL.Record({
  'triggerReason' : IDL.Opt(TriggerReason),
  'priceAtTrigger' : IDL.Float64,
  'crypto' : IDL.Text,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Nat,
  'signalType' : SignalType,
});
export const Preferences = IDL.Record({
  'theme' : IDL.Text,
  'notifications' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearAlerts' : IDL.Func([], [], []),
  'fetchTopCryptoNews' : IDL.Func([], [IDL.Text], []),
  'fetchTopCryptos' : IDL.Func([], [IDL.Text], []),
  'getAlertHistory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(SignalType)],
      [IDL.Vec(Alert)],
      ['query'],
    ),
  'getAlertStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getAlertsLast24Hours' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCryptoAlertHistory' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
  'getTheme' : IDL.Func([], [IDL.Text], ['query']),
  'initializeUser' : IDL.Func([Preferences], [], []),
  'purgeOldAlerts' : IDL.Func([], [], []),
  'saveAlert' : IDL.Func(
      [IDL.Text, SignalType, IDL.Opt(TriggerReason), IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTheme' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SignalType = IDL.Variant({
    'buy' : IDL.Null,
    'hold' : IDL.Null,
    'sell' : IDL.Null,
  });
  const TriggerReason = IDL.Variant({
    'trendFollowing' : IDL.Bool,
    'priceBreak' : IDL.Text,
    'takeProfit' : IDL.Opt(IDL.Float64),
    'rsiBelow30' : IDL.Text,
    'riskReward' : IDL.Opt(IDL.Float64),
    'stopLoss' : IDL.Opt(IDL.Float64),
    'macdCrossover' : IDL.Text,
    'rsiAbove70' : IDL.Text,
  });
  const Alert = IDL.Record({
    'triggerReason' : IDL.Opt(TriggerReason),
    'priceAtTrigger' : IDL.Float64,
    'crypto' : IDL.Text,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Nat,
    'signalType' : SignalType,
  });
  const Preferences = IDL.Record({
    'theme' : IDL.Text,
    'notifications' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearAlerts' : IDL.Func([], [], []),
    'fetchTopCryptoNews' : IDL.Func([], [IDL.Text], []),
    'fetchTopCryptos' : IDL.Func([], [IDL.Text], []),
    'getAlertHistory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(SignalType)],
        [IDL.Vec(Alert)],
        ['query'],
      ),
    'getAlertStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getAlertsLast24Hours' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCryptoAlertHistory' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
    'getTheme' : IDL.Func([], [IDL.Text], ['query']),
    'initializeUser' : IDL.Func([Preferences], [], []),
    'purgeOldAlerts' : IDL.Func([], [], []),
    'saveAlert' : IDL.Func(
        [IDL.Text, SignalType, IDL.Opt(TriggerReason), IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTheme' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };