/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_header {
    value: string;
    name: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Position {
    quantity: number;
    symbol: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Trade {
    id: bigint;
    direction: Direction;
    date: string;
    crypto: string;
    notes: string;
    rationale: string;
    quantity: number;
    entryPrice: number;
    exitPrice?: number;
    outcome: string;
}
export interface Preferences {
    theme: string;
    notifications: boolean;
}
export interface Alert {
    triggerReason?: TriggerReason;
    priceAtTrigger: number;
    crypto: string;
    timestamp: bigint;
    confidence: bigint;
    signalType: SignalType;
}
export type TriggerReason = {
    __kind__: "trendFollowing";
    trendFollowing: boolean;
} | {
    __kind__: "priceBreak";
    priceBreak: string;
} | {
    __kind__: "takeProfit";
    takeProfit: number | null;
} | {
    __kind__: "rsiBelow30";
    rsiBelow30: string;
} | {
    __kind__: "riskReward";
    riskReward: number | null;
} | {
    __kind__: "stopLoss";
    stopLoss: number | null;
} | {
    __kind__: "macdCrossover";
    macdCrossover: string;
} | {
    __kind__: "rsiAbove70";
    rsiAbove70: string;
};
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Direction {
    long_ = "long",
    short_ = "short"
}
export enum SignalType {
    buy = "buy",
    hold = "hold",
    sell = "sell"
}
export interface backendInterface {
    addPosition(symbol: string, quantity: number): Promise<void>;
    addToWatchlist(coin: string): Promise<void>;
    addTrade(trade: Trade): Promise<void>;
    clearAlerts(): Promise<void>;
    fetchTopCryptoNews(): Promise<string>;
    fetchTopCryptos(): Promise<string>;
    getAlertHistory(filterCrypto: string | null, filterSignal: SignalType | null): Promise<Array<Alert>>;
    getAlertStats(): Promise<[bigint, bigint, bigint]>;
    getAlertsLast24Hours(): Promise<Array<Alert>>;
    getCryptoAlertHistory(crypto: string): Promise<Array<Alert>>;
    getJournal(): Promise<Array<Trade>>;
    getPortfolio(): Promise<Array<Position>>;
    getTheme(): Promise<string>;
    getWatchlist(): Promise<Array<string>>;
    initializeUser(preferences: Preferences): Promise<void>;
    purgeOldAlerts(): Promise<void>;
    removeFromJournal(tradeId: bigint): Promise<void>;
    removeFromWatchlist(coin: string): Promise<void>;
    removePosition(symbol: string): Promise<void>;
    saveAlert(crypto: string, signalType: SignalType, triggerReason: TriggerReason | null, confidence: bigint, priceAtTrigger: number): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateTheme(theme: string): Promise<void>;
}
import type { Alert as _Alert, Direction as _Direction, SignalType as _SignalType, Trade as _Trade, TriggerReason as _TriggerReason } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPosition(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPosition(arg0, arg1);
            return result;
        }
    }
    async addToWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async addTrade(arg0: Trade): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrade(to_candid_Trade_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrade(to_candid_Trade_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearAlerts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAlerts();
            return result;
        }
    }
    async fetchTopCryptoNews(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTopCryptoNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTopCryptoNews();
            return result;
        }
    }
    async fetchTopCryptos(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTopCryptos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTopCryptos();
            return result;
        }
    }
    async getAlertHistory(arg0: string | null, arg1: SignalType | null): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertHistory(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertHistory(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertStats(): Promise<[bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertStats();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertStats();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getAlertsLast24Hours(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsLast24Hours();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsLast24Hours();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoAlertHistory(arg0: string): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoAlertHistory(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoAlertHistory(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournal(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournal();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournal();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolio(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio();
            return result;
        }
    }
    async getTheme(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTheme();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTheme();
            return result;
        }
    }
    async getWatchlist(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async initializeUser(arg0: Preferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeUser(arg0);
            return result;
        }
    }
    async purgeOldAlerts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purgeOldAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purgeOldAlerts();
            return result;
        }
    }
    async removeFromJournal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromJournal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromJournal(arg0);
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async removePosition(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePosition(arg0);
            return result;
        }
    }
    async saveAlert(arg0: string, arg1: SignalType, arg2: TriggerReason | null, arg3: bigint, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAlert(arg0, to_candid_SignalType_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAlert(arg0, to_candid_SignalType_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateTheme(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTheme(arg0);
            return result;
        }
    }
}
function from_candid_Alert_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Direction_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SignalType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalType): SignalType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TriggerReason_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TriggerReason): TriggerReason {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TriggerReason]): TriggerReason | null {
    return value.length === 0 ? null : from_candid_TriggerReason_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    triggerReason: [] | [_TriggerReason];
    priceAtTrigger: number;
    crypto: string;
    timestamp: bigint;
    confidence: bigint;
    signalType: _SignalType;
}): {
    triggerReason?: TriggerReason;
    priceAtTrigger: number;
    crypto: string;
    timestamp: bigint;
    confidence: bigint;
    signalType: SignalType;
} {
    return {
        triggerReason: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.triggerReason)),
        priceAtTrigger: value.priceAtTrigger,
        crypto: value.crypto,
        timestamp: value.timestamp,
        confidence: value.confidence,
        signalType: from_candid_SignalType_n16(_uploadFile, _downloadFile, value.signalType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    direction: _Direction;
    date: string;
    crypto: string;
    notes: string;
    rationale: string;
    quantity: number;
    entryPrice: number;
    exitPrice: [] | [number];
    outcome: string;
}): {
    id: bigint;
    direction: Direction;
    date: string;
    crypto: string;
    notes: string;
    rationale: string;
    quantity: number;
    entryPrice: number;
    exitPrice?: number;
    outcome: string;
} {
    return {
        id: value.id,
        direction: from_candid_Direction_n21(_uploadFile, _downloadFile, value.direction),
        date: value.date,
        crypto: value.crypto,
        notes: value.notes,
        rationale: value.rationale,
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        exitPrice: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.exitPrice)),
        outcome: value.outcome
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trendFollowing: boolean;
} | {
    priceBreak: string;
} | {
    takeProfit: [] | [number];
} | {
    rsiBelow30: string;
} | {
    riskReward: [] | [number];
} | {
    stopLoss: [] | [number];
} | {
    macdCrossover: string;
} | {
    rsiAbove70: string;
}): {
    __kind__: "trendFollowing";
    trendFollowing: boolean;
} | {
    __kind__: "priceBreak";
    priceBreak: string;
} | {
    __kind__: "takeProfit";
    takeProfit: number | null;
} | {
    __kind__: "rsiBelow30";
    rsiBelow30: string;
} | {
    __kind__: "riskReward";
    riskReward: number | null;
} | {
    __kind__: "stopLoss";
    stopLoss: number | null;
} | {
    __kind__: "macdCrossover";
    macdCrossover: string;
} | {
    __kind__: "rsiAbove70";
    rsiAbove70: string;
} {
    return "trendFollowing" in value ? {
        __kind__: "trendFollowing",
        trendFollowing: value.trendFollowing
    } : "priceBreak" in value ? {
        __kind__: "priceBreak",
        priceBreak: value.priceBreak
    } : "takeProfit" in value ? {
        __kind__: "takeProfit",
        takeProfit: from_candid_opt_n15(_uploadFile, _downloadFile, value.takeProfit)
    } : "rsiBelow30" in value ? {
        __kind__: "rsiBelow30",
        rsiBelow30: value.rsiBelow30
    } : "riskReward" in value ? {
        __kind__: "riskReward",
        riskReward: from_candid_opt_n15(_uploadFile, _downloadFile, value.riskReward)
    } : "stopLoss" in value ? {
        __kind__: "stopLoss",
        stopLoss: from_candid_opt_n15(_uploadFile, _downloadFile, value.stopLoss)
    } : "macdCrossover" in value ? {
        __kind__: "macdCrossover",
        macdCrossover: value.macdCrossover
    } : "rsiAbove70" in value ? {
        __kind__: "rsiAbove70",
        rsiAbove70: value.rsiAbove70
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    hold: null;
} | {
    sell: null;
}): SignalType {
    return "buy" in value ? SignalType.buy : "hold" in value ? SignalType.hold : "sell" in value ? SignalType.sell : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): Direction {
    return "long" in value ? Direction.long : "short" in value ? Direction.short : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Direction_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SignalType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): _SignalType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TriggerReason_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TriggerReason): _TriggerReason {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TriggerReason | null): [] | [_TriggerReason] {
    return value === null ? candid_none() : candid_some(to_candid_TriggerReason_n24(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType | null): [] | [_SignalType] {
    return value === null ? candid_none() : candid_some(to_candid_SignalType_n7(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    direction: Direction;
    date: string;
    crypto: string;
    notes: string;
    rationale: string;
    quantity: number;
    entryPrice: number;
    exitPrice?: number;
    outcome: string;
}): {
    id: bigint;
    direction: _Direction;
    date: string;
    crypto: string;
    notes: string;
    rationale: string;
    quantity: number;
    entryPrice: number;
    exitPrice: [] | [number];
    outcome: string;
} {
    return {
        id: value.id,
        direction: to_candid_Direction_n3(_uploadFile, _downloadFile, value.direction),
        date: value.date,
        crypto: value.crypto,
        notes: value.notes,
        rationale: value.rationale,
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice ? candid_some(value.exitPrice) : candid_none(),
        outcome: value.outcome
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "trendFollowing";
    trendFollowing: boolean;
} | {
    __kind__: "priceBreak";
    priceBreak: string;
} | {
    __kind__: "takeProfit";
    takeProfit: number | null;
} | {
    __kind__: "rsiBelow30";
    rsiBelow30: string;
} | {
    __kind__: "riskReward";
    riskReward: number | null;
} | {
    __kind__: "stopLoss";
    stopLoss: number | null;
} | {
    __kind__: "macdCrossover";
    macdCrossover: string;
} | {
    __kind__: "rsiAbove70";
    rsiAbove70: string;
}): {
    trendFollowing: boolean;
} | {
    priceBreak: string;
} | {
    takeProfit: [] | [number];
} | {
    rsiBelow30: string;
} | {
    riskReward: [] | [number];
} | {
    stopLoss: [] | [number];
} | {
    macdCrossover: string;
} | {
    rsiAbove70: string;
} {
    return value.__kind__ === "trendFollowing" ? {
        trendFollowing: value.trendFollowing
    } : value.__kind__ === "priceBreak" ? {
        priceBreak: value.priceBreak
    } : value.__kind__ === "takeProfit" ? {
        takeProfit: value.takeProfit ? candid_some(value.takeProfit) : candid_none()
    } : value.__kind__ === "rsiBelow30" ? {
        rsiBelow30: value.rsiBelow30
    } : value.__kind__ === "riskReward" ? {
        riskReward: value.riskReward ? candid_some(value.riskReward) : candid_none()
    } : value.__kind__ === "stopLoss" ? {
        stopLoss: value.stopLoss ? candid_some(value.stopLoss) : candid_none()
    } : value.__kind__ === "macdCrossover" ? {
        macdCrossover: value.macdCrossover
    } : value.__kind__ === "rsiAbove70" ? {
        rsiAbove70: value.rsiAbove70
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    long: null;
} | {
    short: null;
} {
    return value == Direction.long ? {
        long_: null
    } : value == Direction.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): {
    buy: null;
} | {
    hold: null;
} | {
    sell: null;
} {
    return value == SignalType.buy ? {
        buy: null
    } : value == SignalType.hold ? {
        hold: null
    } : value == SignalType.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
